// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace naya {
	
	
	public partial class Print {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder StyleSection;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder LinkSection;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentSection;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ScriptSection;
	}
}
