// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace naya {
	
	
	public partial class StudentViewer {
		
		protected System.Web.UI.WebControls.Content head;
		
		protected System.Web.UI.WebControls.Content link;
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.HtmlControls.HtmlForm pageForm;
		
		protected System.Web.UI.WebControls.GridView StudentsGridView;
		
		protected System.Web.UI.WebControls.LinkButton lnkUpdate;
		
		protected System.Web.UI.WebControls.LinkButton lnkCancel;
		
		protected System.Web.UI.WebControls.LinkButton lnkEdit;
		
		protected System.Web.UI.WebControls.LinkButton lnkDelete;
		
		protected System.Web.UI.WebControls.LinkButton linkView;
		
		protected System.Web.UI.WebControls.LinkButton lnkInsert;
		
		protected System.Web.UI.WebControls.ObjectDataSource ObjectDataSourceStudents;
		
		protected System.Web.UI.WebControls.TextBox tbRollNo;
		
		protected System.Web.UI.WebControls.TextBox tbFirstName;
		
		protected System.Web.UI.WebControls.TextBox tbLastName;
		
		protected System.Web.UI.WebControls.TextBox tbClass;
		
		protected System.Web.UI.WebControls.TextBox tbSection;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.Button btnAddStudent;
		
		protected System.Web.UI.WebControls.TextBox tbDisabledRoll;
		
		protected System.Web.UI.WebControls.HiddenField tbHiddenId;
		
		protected System.Web.UI.WebControls.TextBox tbPhysics;
		
		protected System.Web.UI.WebControls.TextBox tbChemistry;
		
		protected System.Web.UI.WebControls.TextBox tbMathematics;
		
		protected System.Web.UI.WebControls.TextBox tbComputing;
		
		protected System.Web.UI.WebControls.TextBox tbEnglish;
		
		protected System.Web.UI.WebControls.Button btnAddMarks;
		
		protected System.Web.UI.WebControls.Content script;
	}
}
